
species: human
read_len: 100
genome_refcode: GRCh38
endtype: pe
sampleCSVpath: /SAN/vyplab/first_weeks/TDP_CHX_CLONES_GLIA/sample_sheet.csv
# master directory in which output from individual rules is stored (within individual subdirectories, unless overriden below)
#the top level output folder where all the output files are going to be written
#now it will sound insane, but I recommend you use full paths to preserve where the data is stored as configs are saved after runs
project_top_level:   /SAN/vyplab/first_weeks/TDP_CHX_CLONES_GLIA/
#below you can specify the names of rulesubdirectories
#if the provided path string is RELATIVE, the string will be joined with project_top_level to form the output directory path
#if the provided path string is ABSOLUTE, the output for the given rule will be stored in the provided string (NOT WITHIN project_top_level)
#In practice leaving as relative defaults is best option...
run_name: tdp_splicing
majiq_top_level: majiq/
#directory of all the already aligned bam files, this is necessary for building the majic data index from this data
bam_dir: /SAN/vyplab/first_weeks/TDP_CHX_CLONES_GLIA/STAR_aligned/
#for transcriptome primary_assembly
scallop_output: scallop_output/
stringtie_output: stringtie_output/
#one of empty,unstranded, second, first
scallop_strand: empty


#what's between the sample name and the end of the bam?
#Mine all look like this M323K_HET_1_unique_rg_fixed.bam so my suffix is _unique_rg_fixed.bam
bam_suffix: ".Aligned.sorted.out"


majiq_extra_parameters:
majiq_psi_extra_parameters:
extra_voila_parameters:
  threshold: "0.1"
#options are --cutoff deltaPSI cutoff for writing out junctions and upincase, T or False
# annotated_junctions_extra_parameters:
#   cutoff: 0.15
#   upincase: TRUE
annotated_junctions_extra_parameters:
  cutoff: 0.1

# fasta: /SAN/vyplab/vyplab_reference_genomes/sequence/mouse/gencode/GRCm38.primary_assembly.genome.fa
# gtf: /SAN/vyplab/vyplab_reference_genomes/annotation/mouse/gencode/gencode.vM22.annotation.gtf
# gff3: /SAN/vyplab/vyplab_reference_genomes/annotation/mouse/gencode/gencode.vM22.annotation.gff3

fasta: /SAN/vyplab/vyplab_reference_genomes/sequence/human/gencode/GRCh38.primary_assembly.genome.fa
gtf: /SAN/vyplab/vyplab_reference_genomes/annotation/human/GRCh38/gencode.v38.annotation.gtf
gff3: /SAN/vyplab/vyplab_reference_genomes/annotation/human/GRCh38/gencode.v38.annotation.gff3

#the path where your samtools is installed
samtools_path: /share/apps/genomics/samtools-1.9/bin/samtools
# cufflinks_path: /share/apps/genomics/cufflinks-2.2.1/bin/cufflinks
majiq_path: /SAN/vyplab/alb_projects/pipelines/splicing/env/bin/python3 /SAN/vyplab/alb_projects/pipelines/splicing/env/bin/majiq
voila_path: /SAN/vyplab/alb_projects/pipelines/splicing/env/bin/python3 /SAN/vyplab/alb_projects/pipelines/splicing/env/bin/voila

majiq_path_old: /SAN/vyplab/alb_projects/pipelines/splicing/env/bin/python3 /SAN/vyplab/alb_projects/pipelines/splicing/env/bin/majiq
voila_path_old: /SAN/vyplab/alb_projects/pipelines/splicing/env/bin/python3 /SAN/vyplab/alb_projects/pipelines/splicing/env/bin/voila
#########################
## Scallop PARAMETERS
#########################
scallop_path: /SAN/vyplab/alb_projects/tools/scallop-0.10.4/src/scallop
scallop_extra_parameters:
  min_transcript_length_increase: 25
  min_single_exon_coverage: 15
  min_transcript_length_base: 50
  min_transcript_length_increase: 10
  min_transcript_coverage: 0.01
#########################
##SCALLOP HELPER TOOLS PATHS######
#########################
gffcompare: /SAN/vyplab/alb_projects/tools/gffcompare-0.11.6.Linux_x86_64/gffcompare
gtfcuff: /SAN/vyplab/alb_projects/tools/rnaseqtools-1.0.3/gtfcuff/gtfcuff
gtfmerge: /SAN/vyplab/alb_projects/tools/rnaseqtools-1.0.3/gtfmerge/gtfmerge
gffread: /SAN/vyplab/alb_projects/tools/gffread-0.11.8.Linux_x86_64/gffread


# #scallop configurations
# scallop_path: /SAN/vyplab/alb_projects/tools/scallop-0.10.4/src/scallop
# scallop_extra_parameters:
#   library_type: first
#   min_transcript_length_increase: 25
#


# ###### Whippets configurations
# # return of the whippets, whippets strikes back
# whippet_bin: /SAN/vyplab/alb_projects/tools/julia_pkgdir/v0.6/Whippet/bin/
# whippet_indicies: /SAN/vyplab/vyplab_reference_genomes/whippets_index/
# whippet_extra_parameters:
#   bam-min-reads: 10
# # -------------------------- Global configurations which shouldn't need to be
# # -------------------------- adjusted.
#
# julia: /SAN/vyplab/alb_projects/tools/julia-9d11f62bcb/bin/julia